### ISSUE TITLE
Algorithm To Simplify Boolean Equation

### ISSUE THREAD

**Issue by menthy-wu** [acm-ucr/r-tools#21]
<img width="116" alt="image" src="https://github.com/acm-ucr/r-tools/assets/73259022/4007d82c-d228-40e5-be22-d4e926f4cf60">
to
<img width="73" alt="image" src="https://github.com/acm-ucr/r-tools/assets/73259022/c94d6ee6-7d3a-4995-914d-f32b2f71aa14">

**Comment by NovaSagittarii** [comment]
bruh aint no way 💀 

i cant wait to make *game tree bruteforce* algorithm

https://en.wikipedia.org/wiki/Quine%E2%80%93McCluskey_algorithm

**Comment by NovaSagittarii** [comment]
why is there no documentation
