### ISSUE TITLE
Double Check The Example

### ISSUE THREAD

**Issue by menthy-wu** [acm-ucr/r-tools#55]
- double chack the example for selection sort
- I just chatGPTed it lol, so make sure the code is working and there's not syntex error
- make sure it is good code
<img width="1030" alt="image" src="https://github.com/acm-ucr/r-tools/assets/73259022/8465f193-5250-4da9-a85f-9cf62da965ae">

**Comment by Lackline** [comment]
except for JavaScript I'm not sure do we need to do "return arr" at the end of the function (although I checked few sources it should be fine?), everything else seems good to go.
